version: '3.8'

services:
  frontend:
    build: ./frontend
    command: npm run build
    volumes:
      - build_data:/app/build
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: always
    expose:
      - "5000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - build_data:/usr/share/nginx/html

volumes:
  db_data:
  build_data:
